server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    deprecation: ERROR
    org.hibernate: ERROR
    QueuedSender: WARN
    com.codahale.metrics.collectd: ERROR
    io.appform.statesman: DEBUG
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

shards:
  shards:
    - driverClass: org.mariadb.jdbc.Driver
      user: root
      password: password
      url: jdbc:mariadb://mariadb_1/statesman_shard1?createDatabaseIfNotExist=true
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: true
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      checkConnectionWhileIdle: false

    - driverClass: org.mariadb.jdbc.Driver
      user: root
      password: password
      url: jdbc:mariadb://mariadb_2/statesman_shard2?createDatabaseIfNotExist=true
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: true
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      checkConnectionWhileIdle: false

swagger:
  resourcePackage: io.appform.statesman.server.resources
  title: Statesman
  description: Statesman Backend

httpActionDefaultConfig:
  connections: 10
  idleTimeOutSeconds: 30
  connectTimeoutMs: 10000
  opTimeoutMs: 10000

eventPublisherConfig:
  server: "http://34.93.41.24/sendBulkMsg"
  queuePath: /tmp/statesman
  connections: 10
  idleTimeOutSeconds: 30
  connectTimeoutMs: 10000
  opTimeoutMs: 10000
  disabled: true

foxtrot:
  endpoint: http://localhost
  accessToken: token


